# -*- coding: utf-8 -*-
"""Generate the *_25 UI variants from their 2.3 originals.

Each 2.5 UI is the 2.3 UI with a small, explicit set of substitutions: the
generation subprocess is pointed at `ltx_pipelines_25` (the LTX-2.5 shim), the
displayed model paths point at models/2.5/, the window title says 2.5, and the
Gradio port is moved so a 2.5 UI and its 2.3 sibling can run side by side.

Every substitution is asserted: if an anchor stops matching (because the 2.3 UI
was edited upstream), this script fails loudly instead of writing a file that
looks ported but silently still runs 2.3.

Run:  python _make_25_uis.py
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent

CKPT_25 = "./models/2.5/diffusion_models/ltx-2.5-22b-distilled-transformer-bf16.safetensors"
GEMMA_25 = "./models/2.5/text_encoders/gemma4-12b-with-proj-ltx-2.5-bf16.safetensors"
UPS_25 = "./models/2.5/latent_upscale_models/ltx-2.5-latent-spatial-upscaler-x2-bf16-1.0.safetensors"

BANNER = '''"""LTX-2.5 variant of {orig} -- GENERATED by _make_25_uis.py, do not hand-edit
without also updating that script (or it will be overwritten on regeneration).

Differences from the 2.3 original:
  - Generation goes through `ltx_pipelines_25` (the LTX-2.5 shim over
    `ltx25_backend`, i.e. the ComfyUI route) instead of `ltx_pipelines.*`.
    `ltx_pipelines` has no 2.5 support -- see MEMORIAL.md, section "LTX-2.5".
  - Model paths shown in the UI point at models/2.5/. They are display-only on
    this route: the actual checkpoints are chosen inside the ComfyUI workflow.
  - Gradio port moved to {port} so this can run alongside the 2.3 UI.

Options that do not carry over to the 2.5 ComfyUI route (LoRAs, quantization,
torch.compile, TeaCache, step count, audio-conditioned generation) are still
shown by the inherited UI but are reported as ignored by the shim at run time.
"""
'''

# (source, dest, port, [(anchor, replacement), ...])
JOBS = [
    (
        "web_ui_v4.py", "web_ui_v4_25.py", 7960,
        [
            ('sys.executable, "-m", "ltx_pipelines.distilled",',
             'sys.executable, "-m", "ltx_pipelines_25",'),
            ('title="LTX-2.3 Studio + Queue"', 'title="LTX-2.5 Studio + Queue"'),
            # Ancora atualizada 2026-09-06: a linha original mudou desde que
            # este job foi escrito (LTX_UI_HOST + theme/css moveram pro
            # launch() na migracao Gradio 6, ver CLAUDE.md); a versao velha
            # nao batia mais e o gerador falhava alto, como projetado.
            ('demo.launch(server_name=os.environ.get("LTX_UI_HOST", "127.0.0.1"), share=False, theme=theme, css=css)',
             'demo.launch(server_name=os.environ.get("LTX_UI_HOST", "127.0.0.1"), share=False, server_port=7960,\n'
             '                theme=theme, css=css)'),
            # Model-variant selector (2026-09-06): the 2.3 original has no
            # concept of "variant" (distilled/dev/gguf-q6k are LTX-2.5-only,
            # see ltx25_backend.VARIANTS/GGUF_VARIANTS), so this whole block
            # only exists in the generated 2.5 file, never in web_ui_v4.py.
            # Reads the choice list live off ltx25_backend instead of a
            # hardcoded copy, so it never drifts from what the backend
            # actually supports.
            ('from collections import deque',
             'from collections import deque\nimport ltx25_backend'),
            ('                checkpoint_path = gr.Textbox(label="Checkpoint", value=DEFAULT_CHECKPOINT)\n'
             '                gemma_path = gr.Textbox(label="Gemma Root", value=DEFAULT_GEMMA)\n'
             '                upsampler_path = gr.Textbox(label="Upsampler", value=DEFAULT_UPSAMPLER)',
             '                checkpoint_path = gr.Textbox(label="Checkpoint", value=DEFAULT_CHECKPOINT)\n'
             '                gemma_path = gr.Textbox(label="Gemma Root", value=DEFAULT_GEMMA)\n'
             '                upsampler_path = gr.Textbox(label="Upsampler", value=DEFAULT_UPSAMPLER)\n'
             '                variant_dd = gr.Dropdown(\n'
             '                    label="Model variant",\n'
             '                    choices=sorted(ltx25_backend.VARIANTS) + sorted(ltx25_backend.GGUF_VARIANTS),\n'
             '                    value=ltx25_backend.DEFAULT_VARIANT,\n'
             '                    info="distilled/dev/etc. rodam o checkpoint safetensors; gguf-* trocam pro "\n'
             '                         "UnetLoaderGGUF. Ver MEMORIAL/CLAUDE.md pelas diferencas de velocidade "\n'
             '                         "e o que ainda nao foi validado em cada variante.",\n'
             '                )'),
            ('        auto_continue_last_frame,\n'
             '        checkpoint_path, gemma_path, upsampler_path,\n'
             '        img1_path, img1_idx, img1_str,',
             '        auto_continue_last_frame,\n'
             '        variant,\n'
             '        checkpoint_path, gemma_path, upsampler_path,\n'
             '        img1_path, img1_idx, img1_str,'),
            ('            auto_continue_last_frame,\n'
             '            checkpoint_path, gemma_path, upsampler_path,\n'
             '            i1_img, i1_idx, i1_str,',
             '            auto_continue_last_frame,\n'
             '            variant_dd,\n'
             '            checkpoint_path, gemma_path, upsampler_path,\n'
             '            i1_img, i1_idx, i1_str,'),
            ('        "upsampler_path": upsampler_path,',
             '        "upsampler_path": upsampler_path,\n        "variant": variant,'),
            ('            "--seed", str(int(chunk_seed)),\n        ]',
             '            "--seed", str(int(chunk_seed)),\n'
             '            "--variant", job[\'variant\'],\n        ]'),
        ],
    ),
    (
        "film_maker_ui_v4.py", "film_maker_ui_v4_25.py", 7961,
        [
            ('sys.executable, "-m", "ltx_pipelines.distilled",',
             'sys.executable, "-m", "ltx_pipelines_25",'),
            ('title="LTX-2.3 Film Maker"', 'title="LTX-2.5 Film Maker"'),
            # Ancora atualizada 2026-09-06, mesma causa da de web_ui_v4.py
            # acima (migracao Gradio 6, LTX_UI_HOST).
            ('demo.launch(server_name=os.environ.get("LTX_UI_HOST", "127.0.0.1"), theme=theme)',
             'demo.launch(server_name=os.environ.get("LTX_UI_HOST", "127.0.0.1"), server_port=7961, theme=theme)'),
        ],
    ),
    (
        "music_maker_ui_v2.py", "music_maker_ui_v2_25.py", 7903,
        [
            ('sys.executable, "-m", "ltx_pipelines.music_to_video",',
             'sys.executable, "-m", "ltx_pipelines_25",'),
            ('title="LTX-2 Music Video Maker"', 'title="LTX-2.5 Music Video Maker V2"'),
            ("server_port=7803,", "server_port=7903,"),
        ],
    ),
    (
        "music_maker_ui_v3.py", "music_maker_ui_v3_25.py", 7904,
        [
            ('sys.executable, "-m", "ltx_pipelines.music_to_video",',
             'sys.executable, "-m", "ltx_pipelines_25",'),
            ('title="LTX-2 Music Video Maker V3 - LatentSync 1.6"',
             'title="LTX-2.5 Music Video Maker V3 - LatentSync 1.6"'),
            ("server_port=7804,", "server_port=7904,"),
        ],
    ),
]

COMMON = [
    ('DEFAULT_CHECKPOINT = "./models/ltx-2.3-22b-distilled-fp8.safetensors"',
     f'DEFAULT_CHECKPOINT = "{CKPT_25}"'),
    ('DEFAULT_GEMMA = "./models/gemma3"', f'DEFAULT_GEMMA = "{GEMMA_25}"'),
    ('DEFAULT_UPSAMPLER = "./models/ltx-2.3-spatial-upscaler-x2-1.0.safetensors"',
     f'DEFAULT_UPSAMPLER = "{UPS_25}"'),
]


def port_one(src_name, dst_name, port, patches):
    src = ROOT / src_name
    text = src.read_text(encoding="utf-8")
    problems = []
    for anchor, repl in COMMON + patches:
        n = text.count(anchor)
        if n != 1:
            problems.append(f"  âncora {'ausente' if n == 0 else f'ambígua ({n}x)'}: {anchor!r}")
            continue
        text = text.replace(anchor, repl)
    if problems:
        raise SystemExit(f"[{src_name}] patches não aplicáveis:\n" + "\n".join(problems))

    banner = BANNER.format(orig=src_name, port=port)
    # Keep the original module docstring (if any) right after our banner so the
    # inherited file's own documentation is not lost.
    text = banner + "\n" + text
    (ROOT / dst_name).write_text(text, encoding="utf-8")
    print(f"[ok] {src_name} -> {dst_name} (porta {port})")


if __name__ == "__main__":
    for job in JOBS:
        port_one(*job)
    print("Pronto. Rode os .bat start_*_25.bat correspondentes.")
    sys.exit(0)
