# -*- coding: utf-8 -*-
"""The 6 screenplay prompts (LTX-2.3 prompt-guide style) provided by the user,
plus shared negative prompt. #2 (western) already ran; this covers the rest.
"""

NEGATIVE = (
    "subtitles, captions, written text, logos, watermark, extra characters, duplicate characters, "
    "merged faces, identity swapping, costume changes, wrong speaker, both characters moving their "
    "lips simultaneously, overlapping dialogue, background voices, inaccurate lip sync, deformed "
    "hands, distorted faces, flickering, abrupt cuts, camera teleportation, gibberish speech"
)

PROMPTS = {
    "fantasy": {
        "seconds": 17,
        "prefix": "screenplay_fantasy_2_5",
        "text": "A cinematic high-fantasy scene in a circular ancient stone chamber illuminated by blue moonlight and glowing golden runes. Keep exactly two characters with fixed identities throughout the shot. On the left stands Lyra, a young female mage with long silver hair, a dark-blue cloak and a crystal staff. On the right stands Thoren, a broad-shouldered male warrior with short brown hair, worn steel armor, a round shield and a sword. A huge dragon shadow moves behind a sealed stone archway. The camera begins in a medium two-shot and slowly pushes closer while circling slightly. Wind passes through the chamber, stones vibrate, magical energy hums and restrained orchestral music builds underneath. Spoken dialogue is exclusively in natural Brazilian Portuguese with accurate lip sync and no overlapping speech. Lyra touches a glowing rune, turns toward Thoren and says urgently, “Thoren, as runas despertaram. O dragão sentiu nossa presença.” Lyra closes her mouth. Thoren raises his shield, watches the archway and answers in a deep steady voice, “Mantenha o portal aberto. Eu contenho as chamas.” Thoren closes his mouth. Lyra looks up as the moonlight begins fading and says with shortened breath, “A lua está desaparecendo... restam poucos segundos!” Lyra becomes silent. Thoren plants his feet, points his sword toward the archway and declares with rising force, “É o bastante. Pela última estrela, avance!” The portal flashes at the final word. No subtitles or on-screen text.",
    },
    "scifi": {
        "seconds": 17,
        "prefix": "screenplay_scifi_2_5",
        "text": "A cinematic cyberpunk science-fiction scene inside a dark corporate robotics laboratory. Keep exactly two humanoid androids with clearly different designs and consistent identities. Nia stands on the left, a female android with a smooth porcelain face, short white hair, luminous blue eyes and elegant silver body panels. Orion stands on the right, a taller male android with dark graphite armor, short black synthetic hair, amber eyes and a damaged chest plate exposing faint electrical light. The camera begins in a symmetrical medium close two-shot and slowly moves between them. Blue monitors flicker, rain runs down a panoramic window and red security lights pulse softly. Audio contains quiet machinery, electrical crackling, distant alarms and a low electronic score. Dialogue is exclusively in natural Brazilian Portuguese with subtle synthetic resonance, accurate lip sync and no overlapping voices. Nia studies a holographic scan and says, “Orion, você está escondendo uma memória humana.” Nia closes her mouth. Orion touches the damaged panel in his chest and answers softly, “Não é memória, Nia. É saudade.” Orion becomes silent. Nia lowers the weapon in her hand and says as her blue eyes tremble slightly, “Devo apagá-lo... mas também comecei a sentir.” Nia closes her mouth. Orion extends his hand and answers with quiet urgency, “Então venha comigo. Aprendemos a sonhar.” Nia takes his hand as the alarm grows louder. No subtitles, interface text or additional characters.",
    },
    "anime": {
        "seconds": 18,
        "prefix": "screenplay_anime_2_5",
        "text": "A highly detailed cinematic Japanese anime action sequence in a ruined mountain temple courtyard during a violent night rainstorm, rendered as polished hand-drawn cel animation with sharp ink lines, dramatic shadows and controlled motion blur. Keep exactly two samurai heroes with fixed identities. Akemi stands on the left, a young female samurai with a black ponytail, red lacquered armor, a white scarf and a short glowing katana. Ren stands on the right, a young male samurai with loose dark hair, blue-and-black armor and a long katana surrounded by faint red lightning. Behind them, seven circular demonic portals glow through the rain while several shadowy arms emerge without becoming separate characters. The camera starts low, circles the heroes and pushes closer during the final attack. Audio includes heavy rain, thunder, sandals striking wet stone, metallic impacts, controlled breathing and fast taiko drums. Dialogue is exclusively in energetic Brazilian Portuguese with precise lip sync and no overlapping speech. Akemi blocks a shadow strike and shouts, “Ren, sete portais! Só o Golpe da Lua pode fechá-los!” She closes her mouth. Ren lowers his stance, grips his katana and answers, “Distraia as sombras. Preciso de três batimentos.” Ren becomes silent. Akemi deflects two controlled attacks and calls, “Primeiro! Segundo! Agora — corte o céu!” Akemi closes her mouth. Red lightning gathers along Ren’s blade as he performs one clean upward strike and roars, “Trovão Carmesim: Eclipse Final!” A crescent of light crosses the portals, which collapse in sequence. No subtitles, written attack names, extra heroes or chaotic camera cuts.",
    },
    "alice": {
        "seconds": 15,
        "prefix": "screenplay_alice_2_5",
        "text": "A whimsical family-friendly 3D storybook animation inspired by the dreamlike world of Alice in Wonderland. Keep exactly two speaking characters with consistent appearances. Alice stands on the left, a curious young girl with shoulder-length blonde hair, a blue dress, white apron and striped stockings. The White Rabbit stands on the right, a small male rabbit wearing a burgundy jacket, round spectacles and carrying an oversized golden pocket watch. They are inside a colorful curved hallway filled with differently shaped doors. The doors have decorative faces but do not speak; they only hum a soft wordless melody. The camera follows Alice and the Rabbit in a gentle medium tracking shot as floating teacups drift past. Warm magical lighting, pastel colors and soft sparkling particles create a playful atmosphere. Audio contains ticking clocks, quiet door humming, wooden footsteps and cheerful pizzicato strings. Dialogue is exclusively in friendly Brazilian Portuguese with accurate lip sync and no overlapping voices. Alice leans toward a humming door and asks with bright curiosity, “Coelho, por que as portas estão cantando?” Alice closes her mouth. The Rabbit checks his watch and answers rapidly, “Perderam as chaves! E nós perdemos a hora!” The Rabbit becomes silent. Alice catches a floating cup and says cheerfully, “Tomaremos chá até alguma delas se lembrar.” Alice closes her mouth. The Rabbit’s ears rise as a kettle whistles and he exclaims, “Depressa! A chaleira já está atrasada!” They run toward a glowing round door. No frightening imagery, subtitles or written text.",
    },
    "fairytale": {
        "seconds": 15,
        "prefix": "screenplay_fairytale_2_5",
        "text": "A cinematic fairy-tale animation inside a moonlit castle conservatory filled with white flowers, ivy-covered arches and floating golden lights. Keep exactly two characters with stable identities. Princess Celeste stands on the left, a young adult woman with long dark curls, a pale blue gown, a small silver crown and a crystal rose held carefully in both hands. Darius stands on the right, a mature male royal guardian with short grey hair, a blue cape, polished armor and a sheathed sword. The rose’s final luminous petal begins to fade. The camera opens on a close-up of the crystal rose, then gently pulls back into a medium two-shot and slowly moves toward the characters. Audio contains night birds, soft wind through glass windows, delicate harp music and a quiet magical chime. Dialogue is exclusively in elegant Brazilian Portuguese with clear, distinct voices, accurate lip sync and no overlapping speech. Celeste watches the fading petal and says, “Guardião, a rosa de cristal perdeu sua última pétala.” Celeste closes her mouth. Darius places one hand over his heart and answers in a resonant reassuring voice, “Enquanto houver esperança, o reino continuará respirando.” Darius becomes silent. Celeste lifts her chin, grips the rose and says, “Então abrirei os portões e enfrentarei a feiticeira.” Celeste closes her mouth. Darius draws his sword only halfway, kneels briefly and declares, “Lutarei ao seu lado, até o amanhecer voltar.” The crystal rose emits a warm pulse of light. No subtitles, written text or additional characters.",
    },
}
