"""LTX-2.5 generation backend for the *_25 UIs.

Why this exists (and why the 2.5 UIs can't just reuse the 2.3 code path):
`ltx_pipelines` has no LTX-2.5 support -- no CLI for the split per-component
checkpoints, no Gemma4 text encoder in `ltx_core`, and no NADiffusionDecoder
for the 2.5 video VAE. The ComfyUI route DOES support 2.5 end to end (the
vendored ComfyUI core carries `comfy/ldm/lightricks/vae/na_diffusion_decoder.py`
and the LTXVideo custom node ships official 2.5 workflows), and it is the route
validated in this repo -- 6/6 screenplay prompts generated with video+audio.
See MEMORIAL.md, section "LTX-2.5".

So this module mirrors the role `gguf_backend.py` plays for the 2.3 GGUF path:
keep one ComfyUI server alive, patch the official 2.5 workflow with the UI's
parameters, submit it over the HTTP API, and hand back the produced mp4.

Known gaps in this first version (kept explicit rather than silently wrong):
  - Two-stage (2x latent upscale + refine) IS wired since 2026-08-24, but is
    opt-in: `two_stage=True`, `--two-stage`, or LTX25_TWO_STAGE=1. It is not
    derived from the 2.3 UIs' `--spatial-upsampler-path`, which they pass on
    every run -- keying off it would silently slow every existing render.
  - No LoRA support: the official single-stage 2.5 T2V graph has no LoRA loader
    node, so the 2.3 UIs' LoRA pickers do not carry over.
  - Progress is reported as elapsed wall time, not per-step percentage: the
    ComfyUI HTTP API only exposes a finished job through /history (live
    per-node progress needs the websocket channel, not wired here).
  - Audio is generated by the graph itself (T2A). `disable_audio=True` drops
    the audio track from the muxed output; it does not save the sampling cost.
"""
import contextlib
import json
import math
import os
import shutil
import subprocess
import time
import urllib.error
import urllib.request
import uuid

import comfy_workflow_tool as wf_tool

ROOT = os.path.dirname(os.path.abspath(__file__))
COMFY_ROOT = os.path.join(ROOT, "ComfyUI")
COMFY_SERVER = "http://127.0.0.1:8188"
COMFY_PORT = 8188
COMFY_OUTPUT = os.path.join(COMFY_ROOT, "output")

WORKFLOW_PATH = os.path.join(
    COMFY_ROOT, "custom_nodes", "ComfyUI-LTXVideo", "example_workflows", "2.5",
    "LTX-2.5_T2V_I2V_Single_Stage_Distilled.json",
)
SAVE_NODE_ID = "4852"

# Node ids inside the converted (subgraph-flattened) API graph. These come from
# the official workflow's own node ids, prefixed by their subgraph instance --
# see comfy_workflow_tool.convert(). They are stable as long as the upstream
# workflow file keeps its ids; validated_node_ids() checks that at runtime
# instead of letting a silent mismatch produce a wrong-looking render.
N_POSITIVE = "5508"          # PrimitiveStringMultiline -> positive prompt
N_NEGATIVE = "5509"          # PrimitiveStringMultiline -> negative prompt
N_FPS = "5511"               # PrimitiveFloat -> frame rate
N_SECONDS = "5512"           # PrimitiveFloat -> duration in seconds
N_USE_IMAGE = "5014:5506"    # PrimitiveBoolean -> use image input (I2V)
N_LATENT = "5514:3059"       # EmptyLTXVLatentVideo -> width/height
N_SAVE = SAVE_NODE_ID        # SaveVideo
N_SEED = "5516:4832"         # RandomNoise -> noise_seed
N_LOAD_IMAGE = "2004"        # LoadImage
N_RESIZE = "5014:4990"       # ResizeImageMaskNode
N_ENHANCER_CLIP = "5004:5545"  # CLIPLoader (prompt enhancer)
N_CREATE_VIDEO = "5518:4849"   # CreateVideo (muxes video+audio)
N_IMG2VID = "5514:3159"        # LTXVImgToVideoInplace (holds the video VAE link)
N_CONCAT = "5514:4528"         # LTXVConcatAVLatent (video+audio -> nested latent)
N_UNET = "5004:5569"           # UNETLoader -> transformer checkpoint
N_SAMPLER = "5516:4829"        # SamplerCustomAdvanced
N_CFG_GUIDER = "5516:4828"     # CFGGuider (cfg=1; distilled only)
N_SIGMAS = "5516:4984"         # ManualSigmas (8-step distilled schedule)

# --- two-stage (latent upscale + refine) ---------------------------------
#
# The official two-stage graph is the single-stage one plus a `5517:*` subgraph:
#   stage 1 sampler -> LTXVSeparateAVLatent -> LTXVLatentUpsampler (x2 spatial)
#   -> LTXVImgToVideoInplace -> LTXVConcatAVLatent (re-joins stage 1's AUDIO,
#   which is NOT upscaled) -> SamplerCustomAdvanced with sigmas 0.85..0
#   -> LTXVSeparateAVLatent -> the same VAE decode + CreateVideo + SaveVideo.
#
# Sigmas starting at 0.85 rather than 1.0 make it a partial re-denoise: the
# structure from stage 1 survives and detail is added on top. THAT is why this
# beats Real-ESRGAN for faces -- ESRGAN sharpens the pixels it is given, this
# re-synthesises them at twice the latent resolution.
#
# 40 of 45 node ids are shared with the single-stage graph, so the ordinary
# patching (prompt, size, seed, image, keyframes, audio) applies unchanged. Only
# the loaders move: 5004:* in one graph, 5575:* in the other -- see stage_ids().
WORKFLOW_PATH_TWO_STAGE = os.path.join(
    COMFY_ROOT, "custom_nodes", "ComfyUI-LTXVideo", "example_workflows", "2.5",
    "LTX-2.5_T2V_I2V_Two_Stage_Distilled.json",
)
N2_UPSAMPLER = "5517:4975"     # LTXVLatentUpsampler (spatial x2, latent domain)
N2_IMG2VID = "5517:4970"       # LTXVImgToVideoInplace of the refine pass
N2_SEED = "5517:4967"          # RandomNoise of the refine pass (ships hardcoded 42)
N2_SIGMAS = "5517:4985"        # ManualSigmas "0.85, 0.7250, 0.4219, 0.0"
N2_SAMPLER = "5517:4971"       # SamplerCustomAdvanced of the refine pass


def stage_ids(two_stage: bool) -> dict:
    """Node ids that differ between the two official graphs.

    Both graphs carry ONE set of loaders; they just live under a different
    subgraph instance. Looking them up by name keeps the rest of the patching
    identical instead of forking build_workflow.
    """
    pre = "5575" if two_stage else "5004"
    return {"unet": f"{pre}:5569", "enhancer_clip": f"{pre}:{'5572' if two_stage else '5545'}"}


# Two-stage costs a second sampling pass over FOUR TIMES the tokens (2x in each
# spatial axis), so it is opt-in rather than the default: it is a quality/time
# trade the caller should make, not one to spring on every existing UI run.
TWO_STAGE_DEFAULT = os.environ.get("LTX25_TWO_STAGE", "0").strip().lower() in {"1", "true", "yes", "on"}

# --- model variants -------------------------------------------------------
#
# distilled: the shipped workflow's configuration -- 8 fixed sigmas, CFG 1.
#   At CFG 1 classifier-free guidance degenerates to `cond` (the negative
#   branch cancels exactly), so THE NEGATIVE PROMPT HAS NO EFFECT. That is
#   why burned-in subtitles could not be prompted away on this variant
#   (MEMORIAL.md 3.7 has the A/B evidence, including NAG attempts).
#
# dev: the non-distilled transformer, run with REAL CFG through
#   MultimodalGuider (separate video/audio CFG) and a 15-step LTXVScheduler
#   ramp -- so the negative prompt actually applies. There is no official 2.5
#   dev workflow; this wiring is transcribed from the dev branch of the
#   shipped 2.3 workflow "LTX-2.3_T2V_I2V_Single_Stage_Distilled_Full.json"
#   (nodes 4966/4808/4963/4964/4802), whose widget values are mapped onto
#   input names via each node's /object_info schema.
#   Costs roughly 30 model evaluations per clip against 8, i.e. several times
#   slower than distilled.
VARIANTS = {
    "distilled": "ltx-2.5-22b-distilled-transformer-bf16.safetensors",
    "dev": "ltx-2.5-22b-dev-transformer-bf16.safetensors",
    # MESMO modelo destilado, quantizado em int8 no ARQUIVO: 20,0 GiB contra
    # 39,1. Nao e o mesmo que LTX25_UNET_DTYPE=fp8_e4m3fn, que le os 39 GiB do
    # disco e converte na carga -- aqui o peso ja vem pequeno, e continua int8
    # na VRAM (comfy/ops.py trata `int8_tensorwise`+`convrot` como
    # QuantizedTensor e chama int8_linear a cada forward).
    #
    # Nao existe fp8 do 2.5: o repositorio oficial so publica bf16,
    # comfy-int8-convrot e nvfp4 -- e o nvfp4 exige Blackwell, que a 3090 nao e.
    #
    # ATENCAO ao backend: o ComfyUI desliga o kernel CUDA do comfy-kitchen com
    # torch abaixo de cu130 (temos cu128) e o triton fica desligado por padrao,
    # entao sobra o `eager` -- que faz o int8 funcionar, mas sem tensor core.
    # `--enable-triton-backend` liga o triton sem reinstalar nada.
    "distilled-int8": "ltx-2.5-22b-distilled-transformer-comfy-int8-convrot.safetensors",
    # TESTADO 2026-09-02 (pedido do usuario, antes de rodar a cena wuxia): checkpoint
    # comunitario "RedGraft", 17,0 GiB (menor que o int8 acima, 21,5 GiB). Metadata do
    # safetensors confirma arquitetura AVTransformer3DModel (mesma do 2.5) e formato de
    # quantizacao quant_format=="asym_w4a8_int8" -- peso INT4 assimetrico + ativacao
    # INT8, com escala por grupo (weight_s_rel), escala por canal (weight_s_channel) e
    # codebook Lloyd-Max opcional (weight_codebook). Esse formato JA e nativo do
    # comfy/ops.py (linha ~1204-1223), nao precisa de custom node -- mais agressivo que
    # o "distilled-int8" (que e so int8), nunca medido aqui antes. Arquivo em
    # models/ (raiz), hardlink NTFS para ca (mesmo volume, custo zero).
    "redgraft": "redgraftLTX25Fast2K_ltx25Redgraft.safetensors",
    # TESTADO 2026-09-03 (pedido do usuario): 14,88 GiB, ainda menor que o
    # redgraft (17,0 GiB). Ao contrario do redgraft (fork comunitario, origem
    # incerta), este vem do CONVERSOR OFICIAL: metadata do safetensors tem
    # `converted_by="ComfyUI Kitchen W4A8 INT8-Codebook Converter"` e
    # `converter_url=github.com/Comfy-Org/comfy-kitchen/pull/99` -- mesmo
    # projeto que ja da o kernel nativo `asym_w4a8_int8` (comfy/ops.py). Mesma
    # arquitetura AVTransformer3DModel, `gemma_source_checkpoint` confirma
    # parear com o mesmo gemma4-12b-ltx-v1 ja instalado (models/2.5/
    # text_encoders/). Arquivo em models/ (raiz), hardlink NTFS pra ca.
    "w4a8-v10": "ltx25DistilledW4A8_v10.safetensors",
}
DEFAULT_VARIANT = os.environ.get("LTX25_VARIANT", "distilled").strip().lower()

# Teste comparativo 2026-09-06 (pedido do usuario): GGUF do transformer
# distilled via ComfyUI-GGUF (mesmo node ja usado no 2.3), pra comparar
# qualidade/velocidade contra o bf16 (40 GiB) sem sair do ComfyUI. Ao
# contrario de VARIANTS (que so troca o nome do arquivo no UNETLoader
# existente), GGUF precisa de um node DIFERENTE (UnetLoaderGGUF, saida
# MODEL identica) -- por isso fica numa tabela separada, tratada abaixo
# antes do bloco que preenche `unet_name`. Requer a chave `unet:
# diffusion_models` em ComfyUI/extra_model_paths.yaml (secao ltx_25),
# senao o UnetLoaderGGUF nao acha o arquivo (ele le da categoria "unet",
# nao "diffusion_models").
GGUF_VARIANTS = {
    # ComfyUI lista o arquivo com barra invertida (Windows) no /object_info --
    # "gguf_test/..." com barra normal e rejeitado como "value_not_in_list".
    "gguf-q6k": "gguf_test\\LTX-2.5-Distilled-Q6_K.gguf",
}

# dev sampling defaults, from the 2.3 Full workflow's dev branch
DEV_STEPS = 15
DEV_VIDEO_CFG = 3.0
DEV_AUDIO_CFG = 7.0
DEV_SKIP_BLOCKS = "28"
# Spatio-temporal guidance scale for the dev variant. 0 disables the perturbed
# forward pass entirely (GuiderParameters.do_perturbed() only tests this value).
#
# MEASURED 2026-08-24: STG is INCOMPATIBLE with keyframe guides. The perturbed
# pass swaps in ComfyUI-LTXVideo/stg.py::stg_attention, which returns `v` whole
# for the flagged block. Core's _attention_with_guide_mask partitions Q into
# noisy/tracked groups and assigns each result back into a slice, so a
# full-length `v` lands in a shorter slot:
#   "expanded size of the tensor (4992) must match the existing size (6144)"
# -- 4992/6144 being the clip's own tokens vs. the clip plus one latent frame
# per guide. Hence DEV_STG_WITH_KEYFRAMES. See MEMORIAL.md secao 3.14.
DEV_STG = 1.0
DEV_STG_WITH_KEYFRAMES = 0.0

# Conditioning the generation on a real soundtrack (_apply_audio_conditioning).
# ON by default -- VALIDATED 2026-08-24 on a real 2-scene run.
#
# MEASURE IT WITH THE RIGHT INSTRUMENT. The 2.5 audio VAE is mel-spectrogram +
# vocoder, and vocoder resynthesis does not preserve phase, so WAVEFORM
# correlation reads ~0 even on a perfect match -- that false negative nearly got
# this feature disabled. Compare loudness ENVELOPES with a lag-tolerant
# cross-correlation, and always run the cross-pairing control:
#
#   pareamento          conditioned   invented (before the fix)
#   scene1 x slice1        +0.966         +0.501
#   scene1 x slice2        +0.549         +0.299
#   scene2 x slice2        +0.973         +0.315
#   scene2 x slice1        +0.573         +0.524
#
# Each scene matching ITS OWN slice and not the other is the signal; a single
# high number proves nothing, because any two slices of one song correlate
# (a deliberately mismatched pair still scored +0.885 in one control).
# Set LTX25_AUDIO_COND=0 to turn it off. See MEMORIAL.md secao 3.15.
AUDIO_COND_ENABLED = os.environ.get("LTX25_AUDIO_COND", "1").strip().lower() in {"1", "true", "yes", "on"}

def _default_negative() -> str:
    """Negativo do video: o proprio deste modulo mais os termos comuns do
    `negative_prompt_common.txt` (ver load_common_negative)."""
    proprio = (
        "subtitles, captions, burned-in text, on-screen text, text overlay, watermark, "
        "logo, timestamp, extra characters, duplicate characters, merged faces, "
        "deformed hands, distorted faces, flickering, abrupt cuts, gibberish speech"
    )
    try:
        import sys as _sys
        if ROOT not in _sys.path:
            _sys.path.insert(0, ROOT)
        from script_pipeline.generate_storyboards import load_common_negative
        comum = load_common_negative()
    except Exception:
        comum = ""
    return f"{proprio}, {comum}" if comum else proprio


DEFAULT_NEGATIVE = _default_negative()

# The 12B encoder doubles as the enhancer slot's model: the workflow ships a
# separate gemma4_e2b enhancer checkpoint we don't have locally, and ComfyUI
# validates every combo value even for nodes whose output is switched off.
ENCODER_CKPT = "gemma4-12b-with-proj-ltx-2.5-bf16.safetensors"
# LoadImage is executed even in pure T2V (the graph is static; switches select a
# value, they don't prune execution), and an empty filename makes it try to open
# the input DIRECTORY. Any real file works as an unused placeholder.
PLACEHOLDER_IMAGE = "4d84bf57_i2v_input.png"

_server_proc = None
_server_log_handle = None
_base_api_cache = {}


def _log(msg, log_cb=None):
    """Emit one progress line. When a callback is supplied it owns the output
    (the UIs stream it into their own console); printing here as well would
    duplicate every line in that console."""
    if log_cb:
        log_cb(msg)
    else:
        print(msg, flush=True)


def server_is_up() -> bool:
    try:
        urllib.request.urlopen(f"{COMFY_SERVER}/", timeout=3)
        return True
    except Exception:
        return False


_BOOT_LOCK_PATH = os.path.join(ROOT, "logs", "comfyui_ltx25.boot.lock")
_BOOT_LOCK_STALE_S = 600  # mais que qualquer boot_timeout razoavel


@contextlib.contextmanager
def _boot_lock(wait_s: int = 300):
    """Mutex entre PROCESSOS para a decisao 'o servidor existe? inicio um?'.

    Sem isto, duas UIs abertas ao mesmo tempo podem cada uma concluir
    independentemente que a porta 8188 nao responde e tentar subir o
    ComfyUI -- dois processos disputando a mesma porta e a mesma VRAM. O
    `O_CREAT|O_EXCL` e atomico no Windows tambem: so um `open()` concorrente
    ganha o arquivo, os outros recebem FileExistsError.

    Nao bloqueia para sempre: se a espera estourar `wait_s`, segue sem o lock
    -- e o mesmo comportamento de antes de existir lock nenhum, nunca pior."""
    inicio = time.time()
    fd = None
    while True:
        try:
            fd = os.open(_BOOT_LOCK_PATH, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            os.write(fd, f"{os.getpid()} {time.time()}".encode("ascii"))
            os.close(fd)
            break
        except FileExistsError:
            try:
                idade = time.time() - os.path.getmtime(_BOOT_LOCK_PATH)
            except OSError:
                idade = 0  # sumiu entre o check e agora; tenta de novo
            if idade > _BOOT_LOCK_STALE_S:
                # Lock orfao de um processo que morreu segurando-o.
                try:
                    os.remove(_BOOT_LOCK_PATH)
                except OSError:
                    pass
                continue
            if time.time() - inicio > wait_s:
                break  # desiste do lock, segue sem ele -- nunca pior que antes
            time.sleep(1)
    try:
        yield
    finally:
        try:
            os.remove(_BOOT_LOCK_PATH)
        except OSError:
            pass


def ensure_server(log_cb=None, boot_timeout: int = 300) -> None:
    """Start the ComfyUI server if it isn't already running. Idempotent."""
    global _server_proc, _server_log_handle
    if server_is_up():
        return
    os.makedirs(os.path.join(ROOT, "logs"), exist_ok=True)
    with _boot_lock():
        # Double-check: quem segurou o lock antes de nos pode ter acabado de
        # subir o servidor -- reconferir evita um segundo boot desnecessario.
        if server_is_up():
            return
        _ensure_server_locked(log_cb=log_cb, boot_timeout=boot_timeout)


def _ensure_server_locked(log_cb=None, boot_timeout: int = 300) -> None:
    global _server_proc, _server_log_handle

    def log(msg):
        _log(msg, log_cb)

    log("[ltx25] ComfyUI não está no ar; iniciando servidor (~1min)...")
    env = os.environ.copy()
    env.setdefault("CUDA_VISIBLE_DEVICES", "1")
    env.setdefault("HF_HUB_OFFLINE", "1")
    env.setdefault("PYTHONUNBUFFERED", "1")
    env.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

    python_exe = os.path.join(ROOT, ".venv", "Scripts", "python.exe")
    logs_dir = os.path.join(ROOT, "logs")
    os.makedirs(logs_dir, exist_ok=True)
    _server_log_handle = open(os.path.join(logs_dir, "comfyui_ltx25.log"), "a", encoding="utf-8", buffering=1)
    try:
        # ATENCAO: isto so vale quando ESTE modulo sobe o servidor. Na cadeia de
        # decupagem quem sobe e o estagio dos stills, sem --cache-none, e este
        # ensure_server volta cedo -- ver comfy_launch_args em
        # script_pipeline/generate_storyboards.py.
        import sys as _sys
        if ROOT not in _sys.path:
            _sys.path.insert(0, ROOT)
        from script_pipeline.generate_storyboards import comfy_launch_args
        cmd = comfy_launch_args(python_exe, port=COMFY_PORT, cache_none=True,
                                extra=["--disable-auto-launch"])
        log("[ltx25] ComfyUI: " + " ".join(cmd[3:]))
        _server_proc = subprocess.Popen(
            cmd, cwd=COMFY_ROOT, env=env,
            stdout=_server_log_handle, stderr=subprocess.STDOUT,
        )
    except Exception:
        _server_log_handle.close()
        _server_log_handle = None
        raise

    import atexit
    atexit.register(shutdown_server)

    t0 = time.time()
    while time.time() - t0 < boot_timeout:
        if server_is_up():
            log(f"[ltx25] ComfyUI pronto em {time.time()-t0:.1f}s.")
            return
        if _server_proc.poll() is not None:
            rc = _server_proc.returncode
            shutdown_server()
            raise RuntimeError(f"ComfyUI encerrou durante o boot (exit code {rc}).")
        time.sleep(2)
    shutdown_server()
    raise RuntimeError(f"ComfyUI não respondeu em {boot_timeout}s.")


def shutdown_server() -> None:
    global _server_proc, _server_log_handle
    if _server_proc is not None and _server_proc.poll() is None:
        _server_proc.terminate()
        try:
            _server_proc.wait(timeout=15)
        except subprocess.TimeoutExpired:
            _server_proc.kill()
    _server_proc = None
    if _server_log_handle is not None:
        _server_log_handle.close()
        _server_log_handle = None


def _post_json(url, payload):
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.load(r)


def _get_json(url):
    with urllib.request.urlopen(url, timeout=120) as r:
        return json.load(r)


def base_api(two_stage: bool = False) -> dict:
    """Convert the official 2.5 workflow to API format once, then reuse.

    Needs a live server: the converter reads every node's schema from
    /object_info to map positional widget values onto input names.

    two_stage selects the refine graph -- see TWO_STAGE_* and stage_ids().
    """
    key = "two" if two_stage else "one"
    if _base_api_cache.get(key) is None:
        ensure_server()
        path = WORKFLOW_PATH_TWO_STAGE if two_stage else WORKFLOW_PATH
        ui = json.load(open(path, encoding="utf-8"))
        oi = wf_tool.fetch_object_info(COMFY_SERVER)
        api = wf_tool.convert(ui, oi)
        api = wf_tool.prune_to_output(api, SAVE_NODE_ID)
        ids = stage_ids(two_stage)
        expected = [N_POSITIVE, N_NEGATIVE, N_FPS, N_SECONDS, N_USE_IMAGE,
                    N_LATENT, N_SAVE, N_SEED, N_LOAD_IMAGE, N_RESIZE,
                    N_CREATE_VIDEO, N_SAMPLER, N_CFG_GUIDER, N_SIGMAS, N_CONCAT,
                    ids["unet"], ids["enhancer_clip"]]
        if two_stage:
            expected += [N2_UPSAMPLER, N2_IMG2VID, N2_SEED, N2_SIGMAS, N2_SAMPLER]
        missing = [n for n in expected if n not in api]
        if missing:
            raise RuntimeError(
                "O workflow oficial 2.5 mudou de estrutura: nós esperados ausentes "
                f"após a conversão: {missing}. Revise os ids em ltx25_backend.py."
            )
        _base_api_cache[key] = api
    return json.loads(json.dumps(_base_api_cache[key]))  # deep copy per call


def _format_exec_error(messages: list) -> str:
    """Turn ComfyUI's /history error payload into something readable.

    The raw payload is one long JSON line whose useful part -- the failing node
    and the DEEPEST traceback frames -- sits at the very end, so truncating the
    front of it (which is what a plain `json.dumps(...)[:3000]` does) throws away
    exactly the lines that name the tensor. Pull the fields out instead, and when
    the traceback has to be trimmed, keep the tail.
    """
    err = next((d for kind, d in messages if kind == "execution_error"), None)
    if err is None:
        return "Geração falhou:\n" + json.dumps(messages, ensure_ascii=False)[:3000]
    tb = "".join(err.get("traceback") or [])
    if len(tb) > 4000:
        tb = "... (topo do traceback omitido) ...\n" + tb[-4000:]
    return (
        f"Geração falhou no nó {err.get('node_id')} ({err.get('node_type')}):\n"
        f"{err.get('exception_type')}: {err.get('exception_message')}\n\n{tb}"
    )


def _apply_keyframes(api: dict, keyframes: list[tuple[str, int, float]], *, log_cb=None) -> None:
    """Condition the generation on images placed at chosen frame indices
    ("intermediate frames"), not just the first frame.

    LTX 2.5 supports this natively: LTXVAddGuideAdvanced takes an image plus a
    frame_idx and rewrites (positive, negative, latent) together, so guides chain
    -- each node's outputs feed the next. That is what makes a storyboard with
    several beats per scene actually steer the video instead of only setting its
    opening frame.

    frame_idx must be a multiple of 8 for clips of 9+ frames (the node rounds
    down otherwise); we round here so the caller's beat spacing is explicit in
    the submitted graph rather than silently adjusted deeper in.
    """
    guider = api.get(N_CFG_GUIDER) or api.get("9103")
    if guider is None:
        raise RuntimeError("Nenhum guider encontrado para encadear keyframes.")

    positive = guider["inputs"]["positive"]
    negative = guider["inputs"]["negative"]
    # MEASURED: the guides must sit BEFORE LTXVConcatAVLatent, not after. The
    # sampler's latent in this graph is the *combined* audio+video latent, which
    # is a NestedTensor; LTXVAddGuide does `torch.cat` on it and dies with
    # "expected Tensor as element 0 in argument 0, but got NestedTensor".
    # Guiding the plain video latent and letting the concat run afterwards keeps
    # the audio branch untouched, which is also what we want -- a storyboard
    # frame says nothing about the soundtrack.
    concat = api[N_CONCAT]["inputs"]
    latent = concat["video_latent"]
    # Reuse the video VAE link the graph already has on LTXVImgToVideoInplace,
    # rather than hard-coding the loader node id.
    vae = api[N_IMG2VID]["inputs"]["vae"]

    for i, (image_path, frame_idx, strength) in enumerate(keyframes):
        load_id = f"92{i:02d}"
        guide_id = f"93{i:02d}"
        idx = int(frame_idx) // 8 * 8
        api[load_id] = {"class_type": "LoadImage",
                        "inputs": {"image": os.path.basename(image_path)}}
        api[guide_id] = {"class_type": "LTXVAddGuideAdvanced", "inputs": {
            "positive": positive, "negative": negative, "vae": vae, "latent": latent,
            "image": [load_id, 0], "frame_idx": idx, "strength": float(strength),
            # crf/blur_radius trade motion for fidelity; interpolation/crop handle
            # a storyboard frame whose aspect ratio doesn't match the clip. All four
            # are REQUIRED by the node (no defaults applied server-side), so they
            # are spelled out rather than omitted.
            "crf": 29, "blur_radius": 0, "interpolation": "lanczos", "crop": "disabled"}}
        positive = [guide_id, 0]
        negative = [guide_id, 1]
        latent = [guide_id, 2]
        _log(f"[ltx25] keyframe {i+1}/{len(keyframes)}: frame {idx} "
             f"(strength {strength}) <- {os.path.basename(image_path)}", log_cb)

    guider["inputs"]["positive"] = positive
    guider["inputs"]["negative"] = negative
    concat["video_latent"] = latent


def _apply_audio_conditioning(api: dict, audio_path: str, *, frame_rate: float,
                              num_frames: int, log_cb=None) -> None:
    """Generate the video ON TOP of a real soundtrack instead of letting the
    model invent one -- the 2.5 equivalent of 2.3's `--audio-input-path`.

    Two pieces are needed, and one alone is not enough:

    1. LTXVAudioVAEEncode turns the wav into an audio latent, which replaces the
       silent LTXVEmptyLatentAudio in the AV concat.
    2. LTXVSetAudioVideoMaskByTime attaches a per-modality `noise_mask`. Without
       it the sampler noises the whole latent at denoise=1.0 and the music is
       destroyed before the first step -- the encode would be pure waste.

    Mask convention (comfy/samplers.py:642, `out*mask + latent_image*(1-mask)`):
    1 = generate, 0 = keep. So video is masked to 1 everywhere and audio to 0
    everywhere -- the track passes through untouched and conditions every step.
    """
    concat = api[N_CONCAT]["inputs"]
    audio_vae = api["5514:3980"]["inputs"]["audio_vae"]   # from LTXVEmptyLatentAudio
    video_vae = api[N_IMG2VID]["inputs"]["vae"]

    guider = api.get(N_CFG_GUIDER) or api.get("9103")
    if guider is None:
        raise RuntimeError("Nenhum guider encontrado para o condicionamento de áudio.")
    # Take MODEL from the guider rather than N_UNET: whichever variant is in
    # play, the guider holds the link that actually reaches the sampler,
    # patches included.
    model = guider["inputs"]["model"]
    sampler = api[N_SAMPLER]["inputs"]

    api["9400"] = {"class_type": "LoadAudio",
                   "inputs": {"audio": os.path.basename(audio_path)}}
    api["9401"] = {"class_type": "LTXVAudioVAEEncode",
                   "inputs": {"audio": ["9400", 0], "audio_vae": audio_vae}}
    concat["audio_latent"] = ["9401", 0]

    seconds = (int(num_frames) - 1) / float(frame_rate)
    api["9402"] = {"class_type": "LTXVSetAudioVideoMaskByTime", "inputs": {
        "av_latent": sampler["latent_image"],
        "positive": guider["inputs"]["positive"],
        "negative": guider["inputs"]["negative"],
        "model": model, "vae": video_vae, "audio_vae": audio_vae,
        "start_time": 0.0, "end_time": seconds, "video_fps": float(frame_rate),
        # mask_video=True + init 1.0 -> the whole video is generated.
        # mask_audio=False + init 0.0 -> the whole track is preserved.
        "mask_video": True, "mask_init_value_video": 1.0,
        "mask_audio": False, "mask_init_value_audio": 0.0,
        "slope_len": 3}}

    guider["inputs"]["positive"] = ["9402", 0]
    guider["inputs"]["negative"] = ["9402", 1]
    sampler["latent_image"] = ["9402", 2]
    _log(f"[ltx25] áudio de condicionamento: {os.path.basename(audio_path)} "
         f"({seconds:.2f}s) -- o vídeo será gerado sobre a faixa, não com uma inventada.",
         log_cb)


def _apply_dev_variant(api: dict, *, steps: int, video_cfg: float, audio_cfg: float,
                       stg: float = DEV_STG) -> None:
    """Rewire the sampler for the non-distilled (dev) transformer: real CFG via
    MultimodalGuider + an LTXVScheduler sigma ramp, replacing the distilled
    CFG-1 guider and the fixed 8-step ManualSigmas. See VARIANTS.

    `stg` = 0 disables the perturbed (spatio-temporal guidance) forward pass.
    That is REQUIRED when keyframe guides are in play -- see DEV_STG.
    """
    sampler = api[N_SAMPLER]["inputs"]
    latent_link = sampler["latent_image"]
    positive = api[N_CFG_GUIDER]["inputs"]["positive"]
    negative = api[N_CFG_GUIDER]["inputs"]["negative"]
    model = api[N_CFG_GUIDER]["inputs"]["model"]

    # GuiderParameters chain: AUDIO first, VIDEO takes it as `parameters`.
    perturb = not math.isclose(float(stg), 0.0)
    api["9101"] = {"class_type": "GuiderParameters", "inputs": {
        "modality": "AUDIO", "cfg": float(audio_cfg), "stg": float(stg),
        "perturb_attn": perturb,
        "rescale": 0.7, "modality_scale": 3.0, "skip_step": 0, "cross_attn": True}}
    api["9102"] = {"class_type": "GuiderParameters", "inputs": {
        "modality": "VIDEO", "cfg": float(video_cfg), "stg": float(stg),
        "perturb_attn": perturb,
        "rescale": 0.9, "modality_scale": 3.0, "skip_step": 0, "cross_attn": True,
        "parameters": ["9101", 0]}}
    api["9103"] = {"class_type": "MultimodalGuider", "inputs": {
        "model": model, "positive": positive, "negative": negative,
        "parameters": ["9102", 0], "skip_blocks": DEV_SKIP_BLOCKS}}
    api["9104"] = {"class_type": "LTXVScheduler", "inputs": {
        "steps": int(steps), "max_shift": 2.05, "base_shift": 0.95,
        "stretch": True, "terminal": 0.1, "latent": latent_link}}

    sampler["guider"] = ["9103", 0]
    sampler["sigmas"] = ["9104", 0]
    # The CFG-1 guider and the fixed distilled sigmas are now unreachable from
    # the output; drop them so the submitted graph states exactly what it runs.
    api.pop(N_CFG_GUIDER, None)
    api.pop(N_SIGMAS, None)


def build_workflow(
    prompt: str,
    *,
    negative: str = DEFAULT_NEGATIVE,
    width: int = 768,
    height: int = 512,
    num_frames: int = 121,
    frame_rate: float = 24.0,
    seed: int = 42,
    image_path: str | None = None,
    image_strength: float = 1.0,
    disable_audio: bool = False,
    filename_prefix: str = "ltx25",
    variant: str = DEFAULT_VARIANT,
    steps: int | None = None,
    video_cfg: float = DEV_VIDEO_CFG,
    audio_cfg: float = DEV_AUDIO_CFG,
    keyframes: list[tuple[str, int, float]] | None = None,
    audio_conditioning: str | None = None,
    two_stage: bool = TWO_STAGE_DEFAULT,
    log_cb=None,
) -> dict:
    if variant not in VARIANTS and variant not in GGUF_VARIANTS:
        raise ValueError(
            f"variant deve ser um de {sorted(VARIANTS) + sorted(GGUF_VARIANTS)}; "
            f"recebi {variant!r}")
    api = base_api(two_stage)
    ids = stage_ids(two_stage)
    n_unet, n_enh = ids["unet"], ids["enhancer_clip"]

    if variant in GGUF_VARIANTS:
        gguf_rel = GGUF_VARIANTS[variant]
        gguf_path = os.path.join(ROOT, "models", "2.5", "diffusion_models", gguf_rel)
        if not os.path.exists(gguf_path):
            raise FileNotFoundError(
                f"GGUF da variante '{variant}' não encontrado: {gguf_path}")
        # Troca o NODE inteiro (nao so unet_name): UnetLoaderGGUF e um class_type
        # diferente do UNETLoader oficial. Mesma saida (MODEL), entao o resto do
        # grafo nao percebe a troca.
        api[n_unet] = {"class_type": "UnetLoaderGGUF",
                       "inputs": {"unet_name": gguf_rel}}
    else:
        ckpt = VARIANTS[variant]
        ckpt_path = os.path.join(ROOT, "models", "2.5", "diffusion_models", ckpt)
        if not os.path.exists(ckpt_path):
            raise FileNotFoundError(
                f"Checkpoint da variante '{variant}' não encontrado: {ckpt_path}\n"
                "Baixe de Lightricks/LTX-2.5 (diffusion_models/) antes de usar esta variante."
            )
        api[n_unet]["inputs"]["unet_name"] = ckpt

    # --- PRECISAO E DEVICE: os dois botoes que a rota 2.5 nunca apertou -------
    #
    # O workflow oficial carrega o transformer com weight_dtype "default" (bf16,
    # 40 GB) e o encoder Gemma4 no device "default" (GPU, 25 GB). Numa placa de
    # 24,5 GB isso e entregar os dois crus e torcer -- e e a diferenca de fundo
    # para a rota 2.3, que roda um checkpoint fp8 COM orcamento de memoria
    # declarado (`--quantization fp8-cast` mais LTX_TRANSFORMER_GPU_MEMORY; ver
    # CLAUDE.md e model_ledger.transformer(), que so aplica max_memory quando ha
    # quantizacao).
    #
    # MEDIDO 2026-08-27: um clipe de 73 frames a 960x544 fecha em 511 s, e um de
    # 145 frames nao fecha -- encalha primeiro na carga do encoder e, com
    # --cache-none, no decode tiled do VAE, sempre a ~24 GB de 24,5.
    #
    # Os dois padroes sao "default", entao NADA muda sem alguem pedir: a rota
    # validada continua exatamente como estava.
    unet_dtype = os.environ.get("LTX25_UNET_DTYPE", "default")
    if unet_dtype != "default":
        api[n_unet]["inputs"]["weight_dtype"] = unet_dtype
        _log(f"[ltx25] transformer em {unet_dtype} (LTX25_UNET_DTYPE).", log_cb)
    if variant == "dev":
        stg = DEV_STG_WITH_KEYFRAMES if keyframes else DEV_STG
        if keyframes:
            _log("[ltx25] dev + keyframes: STG desligado (stg=0). O passe "
                 "perturbado do STG e incompativel com as guias -- ver DEV_STG. "
                 "Efeito colateral bem-vindo: ~1/3 mais rapido por passo.", log_cb)
        _apply_dev_variant(api, steps=steps or DEV_STEPS,
                           video_cfg=video_cfg, audio_cfg=audio_cfg, stg=stg)

    # --- structural fixes for schema drift in the current ComfyUI core ---
    api[n_enh]["inputs"]["clip_name"] = ENCODER_CKPT
    clip_device = os.environ.get("LTX25_CLIP_DEVICE", "default")
    if clip_device != "default":
        # Encoder na CPU: ele roda UMA vez por clipe e o resultado e um tensor
        # de condicionamento pequeno. Tirar 25 GB da disputa custa tempo de
        # codificacao e devolve espaco para o transformer e para o VAE, que sao
        # quem realmente precisa da placa.
        api[n_enh]["inputs"]["device"] = clip_device
        _log(f"[ltx25] encoder de texto no device '{clip_device}' (LTX25_CLIP_DEVICE).", log_cb)
    rz = api[N_RESIZE]["inputs"]
    rz["scale_method"] = "lanczos"
    for k in ("width", "height", "crop"):
        rz.pop(k, None)
    # resize_type/format are COMFY_DYNAMICCOMBO_V3: the selected key goes in the
    # field itself, its sub-fields come as "<field>.<subfield>" siblings.
    rz["resize_type"] = "scale dimensions"
    rz["resize_type.width"] = width
    rz["resize_type.height"] = height
    rz["resize_type.crop"] = "center"
    api[N_SAVE]["inputs"]["format"] = "auto"
    api[N_SAVE]["inputs"]["format.codec"] = "auto"
    # MEASURED 2026-08-24 -- THE bug behind "the character changes clothes every
    # scene". LTXVImgToVideoInplace.strength is a FLOAT (default 1.0), but the
    # flattened graph carried `false` there: in the source workflow both
    # `strength` and `bypass` are subgraph inputs (sentinel -10), `bypass`
    # resolved and `strength` did not, so the widget fallback picked the wrong
    # index of widgets_values [.., false, .., 0.7] and handed over the boolean.
    # float(False) == 0.0 == conditioning switched off: the image was loaded,
    # resized, preprocessed, VAE-encoded, and then applied with zero weight.
    # Proof: in a 16-scene chain each scene's frame 0 differed from the previous
    # scene's last frame by 65/255 -- the distance between unrelated images.
    # Same failure class as the batch_size union-type bug (MEMORIAL.md secao
    # 3.6); the converter is not to be trusted for widget values, so pin it.
    api[N_IMG2VID]["inputs"]["strength"] = float(image_strength)
    if two_stage:
        # The refine pass has its own LTXVImgToVideoInplace and carries the SAME
        # `false` in strength -- the bug is in the shared subgraph, so it is
        # present once per instance.
        api[N2_IMG2VID]["inputs"]["strength"] = float(image_strength)
        # ...and its own RandomNoise, which the workflow ships hardcoded to 42.
        # Left alone, two runs at different seeds would share the refine noise.
        api[N2_SEED]["inputs"]["noise_seed"] = int(seed)
        _log(f"[ltx25] two-stage: upscale latente x2 + refino "
             f"(sigmas {api[N2_SIGMAS]['inputs']['sigmas']}) -- saída em "
             f"{int(width)*2}x{int(height)*2}, bem mais lento.", log_cb)

    # --- generation parameters ---
    api[N_POSITIVE]["inputs"]["value"] = prompt
    api[N_NEGATIVE]["inputs"]["value"] = negative
    api[N_FPS]["inputs"]["value"] = float(frame_rate)
    # The graph derives the frame count as 1 + floor(fps * seconds / 8) * 8.
    # Feeding seconds = (num_frames - 1)/fps makes that land on num_frames
    # exactly, as long as num_frames is 1 + a multiple of 8 (the model's
    # own constraint).
    api[N_SECONDS]["inputs"]["value"] = (int(num_frames) - 1) / float(frame_rate)
    api[N_LATENT]["inputs"]["width"] = int(width)
    api[N_LATENT]["inputs"]["height"] = int(height)
    api[N_SEED]["inputs"]["noise_seed"] = int(seed)
    api[N_SAVE]["inputs"]["filename_prefix"] = filename_prefix

    if image_path:
        api[N_LOAD_IMAGE]["inputs"]["image"] = os.path.basename(image_path)
        api[N_USE_IMAGE]["inputs"]["value"] = True
    else:
        api[N_LOAD_IMAGE]["inputs"]["image"] = PLACEHOLDER_IMAGE
        api[N_USE_IMAGE]["inputs"]["value"] = False

    if disable_audio:
        api[N_CREATE_VIDEO]["inputs"].pop("audio", None)

    # Applied last: keyframe guides rewrite (positive, negative, latent), so they
    # must chain onto whatever guider the chosen variant left in place.
    if keyframes:
        _apply_keyframes(api, keyframes, log_cb=log_cb)

    # After the guides: those work on the plain VIDEO latent, before the AV
    # concat, while audio conditioning wraps the concat's output. Reversing the
    # order would make the mask node read a latent the guides then replace.
    if audio_conditioning:
        if AUDIO_COND_ENABLED:
            _apply_audio_conditioning(api, audio_conditioning, frame_rate=frame_rate,
                                      num_frames=num_frames, log_cb=log_cb)
        else:
            _log("[ltx25] condicionamento por trilha desligado via LTX25_AUDIO_COND=0: "
                 "o clipe sai com áudio gerado pelo modelo e o movimento não segue "
                 "a batida.", log_cb)

    return api


def stage_input_image(path: str) -> str:
    """Copy an image into ComfyUI/input so LoadImage can see it by basename."""
    return _stage_input(path)


def stage_input_audio(path: str) -> str:
    """Copy an audio file into ComfyUI/input so LoadAudio can see it by basename."""
    return _stage_input(path)


def _stage_input(path: str) -> str:
    dest_dir = os.path.join(COMFY_ROOT, "input")
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, f"{uuid.uuid4().hex[:8]}_{os.path.basename(path)}")
    shutil.copy2(path, dest)
    return dest


def submit_and_wait(api: dict, log_cb=None, timeout: int = 5400,
                    expect_node: str | None = None) -> list[str]:
    """Submit one workflow, block until it finishes, return output filenames.

    `expect_node`: id of the node whose output IS the answer (SAVE_NODE_ID for
    this backend). When given and present in the history, its files are
    returned ALONE -- the flattened scan across every node stays as fallback
    for a graph that doesn't name one. Without this, `generate()` took
    `files[0]` from a scan over EVERY output-producing node in dict-iteration
    order, which is fragile the moment a graph has more than one Save* node
    (a preview node, a two-stage intermediate) -- nothing guarantees the final
    video sorts first."""
    def log(msg):
        _log(msg, log_cb)

    ensure_server(log_cb=log_cb)
    try:
        res = _post_json(f"{COMFY_SERVER}/prompt", {"prompt": api, "client_id": str(uuid.uuid4())})
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", "replace")
        raise RuntimeError(f"ComfyUI rejeitou o workflow (HTTP {e.code}):\n{body[:3000]}") from None

    pid = res.get("prompt_id")
    log(f"[ltx25] enfileirado: {pid}")
    t0 = time.time()
    last_report = 0.0
    while time.time() - t0 < timeout:
        hist = _get_json(f"{COMFY_SERVER}/history/{pid}")
        if pid in hist:
            entry = hist[pid]
            status = entry.get("status", {})
            if status.get("completed") or status.get("status_str") == "success":
                outputs = entry.get("outputs") or {}
                if expect_node and expect_node in outputs:
                    files = [it["filename"] for items in outputs[expect_node].values()
                             for it in (items if isinstance(items, list) else [])
                             if isinstance(it, dict) and it.get("filename")]
                else:
                    if expect_node:
                        log(f"[ltx25] no {expect_node} sem saida no historico; "
                            f"caindo para a varredura de todos os nos.")
                    files = [it["filename"]
                             for _nid, out in outputs.items()
                             for _k, items in out.items()
                             for it in (items if isinstance(items, list) else [])
                             if isinstance(it, dict) and it.get("filename")]
                log(f"[ltx25] concluído em {time.time()-t0:.1f}s -> {files}")
                return files
            if status.get("status_str") == "error":
                raise RuntimeError(_format_exec_error(status.get("messages", [])))
        elapsed = time.time() - t0
        if elapsed - last_report >= 15:
            last_report = elapsed
            log(f"[ltx25] gerando... {elapsed:.0f}s")
        time.sleep(3)
    raise RuntimeError(f"Timeout após {timeout}s.")


def generate(
    prompt: str,
    output_path: str,
    *,
    negative: str = DEFAULT_NEGATIVE,
    width: int = 768,
    height: int = 512,
    num_frames: int = 121,
    frame_rate: float = 24.0,
    seed: int = 42,
    image_path: str | None = None,
    image_strength: float = 1.0,
    disable_audio: bool = False,
    variant: str = DEFAULT_VARIANT,
    steps: int | None = None,
    video_cfg: float = DEV_VIDEO_CFG,
    audio_cfg: float = DEV_AUDIO_CFG,
    keyframes: list[tuple[str, int, float]] | None = None,
    audio_conditioning: str | None = None,
    two_stage: bool = TWO_STAGE_DEFAULT,
    log_cb=None,
    timeout: int = 5400,
) -> str:
    """Generate one LTX-2.5 clip and copy it to *output_path*. Returns that path.

    keyframes: (image_path, frame_idx, strength) placed at chosen points in the
    clip -- the "intermediate frames" path. Images are staged into ComfyUI/input
    automatically.

    audio_conditioning: path to a soundtrack the video should be generated ON,
    replacing the audio the model would otherwise invent. This is the 2.5
    equivalent of 2.3's `--audio-input-path`; see _apply_audio_conditioning."""
    staged = stage_input_image(image_path) if image_path else None
    staged_keys = [(stage_input_image(p), i, s) for p, i, s in (keyframes or [])]
    staged_audio = stage_input_audio(audio_conditioning) if audio_conditioning else None
    # Tudo que _stage_input copiou para ComfyUI/input, para apagar no finally.
    # Nenhuma UI aqui limpava isso: em uso continuo a pasta so cresce, e um
    # nome tipo "a1b2c3d4_shot002.wav" nao diz de qual run veio quando alguem
    # for depurar.
    _staged_paths = [p for p in [staged, staged_audio] if p] + [p for p, _, _ in staged_keys]
    api = build_workflow(
        prompt,
        negative=negative,
        width=width,
        height=height,
        num_frames=num_frames,
        frame_rate=frame_rate,
        seed=seed,
        image_path=staged,
        image_strength=image_strength,
        disable_audio=disable_audio,
        filename_prefix=os.path.splitext(os.path.basename(output_path))[0] or "ltx25",
        variant=variant,
        steps=steps,
        video_cfg=video_cfg,
        audio_cfg=audio_cfg,
        keyframes=staged_keys or None,
        audio_conditioning=staged_audio,
        two_stage=two_stage,
        log_cb=log_cb,
    )
    if variant == "dev":
        _log(f"[ltx25] variante dev: CFG real (vídeo {video_cfg} / áudio {audio_cfg}), "
             f"{steps or DEV_STEPS} passos -- negative prompt ATIVO, mais lento que distilled.", log_cb)
    else:
        # Toda variante que nao e "dev" cai no mesmo caminho destilado de 8 passos
        # (inclusive "redgraft"/"distilled-int8" -- so trocam o ARQUIVO do
        # checkpoint, nao o schedule de amostragem). A mensagem citava sempre
        # "distilled" mesmo quando a variante escolhida era outra -- corrigido
        # 2026-09-02 pra nomear a variante de verdade.
        _log(f"[ltx25] variante {variant}: 8 passos, CFG 1 -- rápido, "
             "mas o negative prompt não tem efeito nesta variante.", log_cb)
    try:
        files = submit_and_wait(api, log_cb=log_cb, timeout=timeout, expect_node=N_SAVE)
        if not files:
            raise RuntimeError("A geração terminou sem produzir arquivo de saída.")
        src = os.path.join(COMFY_OUTPUT, files[0])
        os.makedirs(os.path.dirname(os.path.abspath(output_path)) or ".", exist_ok=True)
        shutil.copy2(src, output_path)
        return output_path
    finally:
        for p in _staged_paths:
            try:
                os.remove(p)
            except OSError:
                pass


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(description="LTX-2.5 text/image-to-video via ComfyUI")
    ap.add_argument("--prompt", required=True)
    ap.add_argument("--output-path", required=True)
    ap.add_argument("--negative", default=DEFAULT_NEGATIVE)
    ap.add_argument("--width", type=int, default=768)
    ap.add_argument("--height", type=int, default=512)
    ap.add_argument("--num-frames", type=int, default=121,
                    help="must be 1 + a multiple of 8 (model constraint)")
    ap.add_argument("--frame-rate", type=float, default=24.0)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--image", default=None, help="first-frame conditioning image (I2V)")
    ap.add_argument("--disable-audio", action="store_true")
    ap.add_argument("--variant", choices=sorted(VARIANTS) + sorted(GGUF_VARIANTS),
                    default=DEFAULT_VARIANT,
                    help="distilled: 8 passos, CFG 1, rápido (negative prompt inerte). "
                         "dev: CFG real, negative prompt ativo, várias vezes mais lento.")
    ap.add_argument("--steps", type=int, default=None, help="passos (só dev; padrão 15)")
    ap.add_argument("--video-cfg", type=float, default=DEV_VIDEO_CFG)
    ap.add_argument("--audio-cfg", type=float, default=DEV_AUDIO_CFG)
    args = ap.parse_args()

    if (args.num_frames - 1) % 8 != 0:
        raise SystemExit(f"--num-frames deve ser 1 + múltiplo de 8; recebi {args.num_frames}")

    out = generate(
        args.prompt, args.output_path,
        negative=args.negative, width=args.width, height=args.height,
        num_frames=args.num_frames, frame_rate=args.frame_rate, seed=args.seed,
        image_path=args.image, disable_audio=args.disable_audio,
        variant=args.variant, steps=args.steps,
        video_cfg=args.video_cfg, audio_cfg=args.audio_cfg,
    )
    print(f"OK -> {out}")
