from pathlib import Path
import json
import subprocess
import uuid
import socket
from .character_schema import CharacterSpec

CONTENT_LIBRARY = Path(r"C:\Users\Public\Documents\My DAZ 3D Library")
DEFAULT_FIGURE_PRESET = CONTENT_LIBRARY / "People" / "Genesis 3 Female" / "Genesis 3 Female.duf"
SCRIPT_LIBRARY_DIR = CONTENT_LIBRARY / "Scripts" / "DAZ Character Director"
SCENE_LIBRARY_DIR = Path(r"C:\Users\user\Documents\DAZ 3D\Studio\My Library\Scenes")
DEFAULT_WARDROBE_PRESET = CONTENT_LIBRARY / "People" / "Genesis 3 Female" / "Clothing" / "Basic Wear" / "Basic Wear.duf"


def resolve_figure_preset(requested: str | None) -> str | None:
    """Use an explicit existing DUF, otherwise fall back to an installed base figure."""
    if requested and Path(requested).is_file():
        return str(Path(requested).resolve())
    if DEFAULT_FIGURE_PRESET.is_file():
        return str(DEFAULT_FIGURE_PRESET)
    return None


def _daz_path(path: str | None) -> str | None:
    return Path(path).resolve().as_posix() if path else None


def create_script(spec: CharacterSpec, output_dir: str, reference: str | None = None, figure_preset: str | None = None) -> Path:
    out = Path(output_dir).resolve(); out.mkdir(parents=True, exist_ok=True)
    figure_preset = _daz_path(resolve_figure_preset(figure_preset))
    wardrobe_preset = _daz_path(str(DEFAULT_WARDROBE_PRESET) if DEFAULT_WARDROBE_PRESET.is_file() else None)
    job_id = uuid.uuid4().hex[:8]
    SCENE_LIBRARY_DIR.mkdir(parents=True, exist_ok=True)
    scene_file = (SCENE_LIBRARY_DIR / f"daz_character_{job_id}.duf").resolve().as_posix()
    thumbnail_file = (SCENE_LIBRARY_DIR / f"daz_character_{job_id}.png").resolve().as_posix()
    # JSON serialization prevents prompt/path text from breaking the DSA source.
    cfg = json.dumps({"spec": spec.__dict__, "reference": reference, "figure_preset": figure_preset,
                      "wardrobe_preset": wardrobe_preset,
                      "scene_file": scene_file, "thumbnail_file": thumbnail_file}, ensure_ascii=False)
    script = f'''// Generated by LTX-2-OPTIMIZED DAZ integration
var cfg = {json.dumps(cfg)};
(function() {{
    var data = JSON.parse(cfg);
    if (data.figure_preset) {{
        print("Loading figure preset: " + data.figure_preset);
        var loaded = App.getContentMgr().openNativeFile(data.figure_preset, true);
        if (!loaded) {{ print("Could not load figure preset: " + data.figure_preset); return; }}
        print("Figure preset loaded successfully.");
    }}
    var figure = Scene.getPrimarySelection();
    if (!figure) {{ print("No Genesis figure loaded. Provide a .duf preset or select a figure first."); return; }}
    Scene.setPrimarySelection(figure);
    if (data.wardrobe_preset) {{
        print("Loading wardrobe preset: " + data.wardrobe_preset);
        if (!App.getContentMgr().openNativeFile(data.wardrobe_preset, true)) {{
            print("Could not load wardrobe preset: " + data.wardrobe_preset);
        }} else {{ print("Wardrobe loaded successfully."); }}
    }}
    var mainWindow = App.getMainWindow();
    if (mainWindow) {{ mainWindow.show(); mainWindow.raise(); mainWindow.activateWindow(); }}
    function set(label, value) {{ var p = figure.findPropertyByLabel(label); if (p) p.setValue(value); }}
    set("Age", data.spec.age); set("Muscularity", data.spec.muscularity);
    set("Height", data.spec.height); set("Weight", data.spec.weight);
    // Hair and outfit are intentionally resolved by the user's DAZ library/presets.
    print("Character spec received: " + data.spec.outfit + " / " + data.spec.hair);
    var saved = Scene.saveScene(data.scene_file);
    if (saved.valueOf() == 0) {{
        Scene.saveThumbnailImage(data.thumbnail_file);
        print("Scene saved: " + data.scene_file);
    }} else {{
        print("Could not save scene: " + data.scene_file);
    }}
}})();
'''
    path = out / f"daz_character_{job_id}.dsa"
    path.write_text(script, encoding="utf-8")
    return path


def run_daz(script: Path, daz_path: str, wait: bool = False) -> str:
    if not Path(daz_path).exists():
        raise FileNotFoundError(f"DAZ Studio não encontrado: {daz_path}")
    # DAZ accepts -script only while creating a new process. A second invocation
    # delegates to the existing instance and silently drops the script argument.
    running = subprocess.run(["tasklist", "/FI", "IMAGENAME eq DAZStudio.exe", "/NH"],
                             capture_output=True, text=True, check=False).stdout.lower()
    if "dazstudio.exe" in running:
        return ("DAZ já está aberto: o script foi criado, mas não foi executado automaticamente. "
                "No DAZ use Scripts > Run Script… e selecione: " + str(script))
    cms_hint = ""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as check:
        check.settimeout(0.5)
        if check.connect_ex(("127.0.0.1", 17237)) != 0:
            cms_hint = ("\nAviso: PostgreSQL CMS do DAZ não está ativo (porta 17237). "
                        "Instale/ative 'PostgreSQL CMS' no DAZ Install Manager para Smart Content; "
                        "a carga de presets por caminho continua funcionando.")
    proc = subprocess.Popen([daz_path, "-noPrompt", "-script", str(script)],
                            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if wait: proc.wait(timeout=600)
    return f"DAZ iniciado (PID {proc.pid}){cms_hint}"
